### ISSUE TITLE
Test Windows build script

### ISSUE THREAD

**Issue by johnjcamilleri** [GrammaticalFramework/gf-rgl#9]
There is a Haskell-free script for building the RGL on Windows, in the file `Make.bat`.
This script is not fully tested. We need a volunteer with access to a Windows machine, and ideally some batch scripting skills, to test it out.

**Comment by johnjcamilleri** [comment]
It seems [Travis CI now supports Windows](https://blog.travis-ci.com/2018-10-11-windows-early-release). Perhaps this is a good way of properly testing the `Make.bat` script.

**Comment by odanoburu** [comment]
before trying the new Travis feature, I'm cleaning the .travis.yml config file (on my travis branch), so that we can build on both linux, mac, and windows, without using docker.

while trying to implement the linux and mac configs, I came across two problems I think @johncamilleri and @Thomas-H can help me with:

- in ubuntu 14 (travis' machine), I can't install gf with the .deb file, because the libtinfo minimum package version is 6, and trusty's version is 5.9. can this lower bound be safely lowered by any chance? if not, I'll either have to revert to using docker (at least for the Linux build) or perhaps we can release a  distro-independent linux binary I could use here?

- in the macOS build, I've followed the tar command instruction in the GF page, but it throws an error about changed owner/permission. is this bsd's tar or gnu-tar? I believe I can make it work by installing gnu-tar, but as I don't have OSX to test on I thought I might ask if someone had run into this error before trying it.

I'm on mobile, so sorry for the lack of log pastes!

**Comment by johnjcamilleri** [comment]
> in ubuntu 14 (travis' machine), I can't install gf with the .deb file, because the libtinfo minimum package version is 6, and trusty's version is 5.9. can this lower bound be safely lowered by any chance? if not, I'll either have to revert to using docker (at least for the Linux build) or perhaps we can release a  distro-independent linux binary I could use here?

No idea about this, sorry.

> in the macOS build, I've followed the tar command instruction in the GF page, but it throws an error about changed owner/permission. is this bsd's tar or gnu-tar? I believe I can make it work by installing gnu-tar, but as I don't have OSX to test on I thought I might ask if someone had run into this error before trying it.

macOS uses BSD tar. I'm sure this command had been tested before so it's unlikely to be wrong.
I guess you don't need to install into `/usr/local` and thus don't need `sudo`, would that help?

**Comment by odanoburu** [comment]
> No idea about this, sorry.

let's see if @Thomas-H can help us with the ubuntu build, then!

> I guess you don't need to install into /usr/local and thus don't need sudo, would that help?

indeed your suggestion works, but then I probably need to set some environment variable so that I don't get this error: 

```
dyld: Library not loaded: /usr/local/lib/libpgf.0.dylib
  Referenced from: /Users/travis/build/odanoburu/gf-rgl/gf-bin/bin/gf
  Reason: image not found
```

thankfully, unpacking to `/usr/local` and using the `--no-same-owner --no-same-permissions` flags works!

> I'm sure this command had been tested before so it's unlikely to be wrong.

yes, but as there are two ways of installing GF on macs and this is the latter, I thought this one might've been the least tested one!

**Comment by odanoburu** [comment]
[it works](https://travis-ci.org/odanoburu/gf-rgl/jobs/448625886), thanks @Thomas-H ! 

what GHC versions is GF supposed to support? in MacOS I'm using 8.2, but in ubuntu trusty the version is 7.6.3 -- is this too old to be supported? I think I can add a more recent version from a hvr's PPA, because it throws two errors when running `Make.hs`:

```
Make.hs:9:34: Module `System.Exit' does not export `die'
Make.hs:13:80:
    Module `System.Directory' does not export `setModificationTime'
```

if we want to support this version of GHC, `die` seems easy enough to substitute, but `directory`'s version is 1.2.0.1, instead of the 1.2.3.0 required by `setModificationTime` (but I can probably install a later version using cabal). should we go for a later GHC or try to fix this?

**Comment by johnjcamilleri** [comment]
> `die` seems easy enough to substitute

Fixed in e30fa893

**Comment by johnjcamilleri** [comment]
> `directory`'s version is 1.2.0.1, instead of the 1.2.3.0 required by `setModificationTime`

Addressed in 62ea7c82 (modification times are simply not copied if `directory` < 1.2.3.0).

**Comment by johnjcamilleri** [comment]
Changed in 5172586a, where we check GHC version instead of `directory` version.

**Comment by odanoburu** [comment]
[new error](https://travis-ci.org/odanoburu/gf-rgl/builds/448799798): 

```
Make.hs:447:15: Not in scope: type constructor or class `Foldable'
```

btw, should I compile `Make.hs` to try and make the builds faster?

**Comment by Thomas-H** [comment]
> [new error](https://travis-ci.org/odanoburu/gf-rgl/builds/448799798):
> 
> ```
> Make.hs:447:15: Not in scope: type constructor or class `Foldable'
> ```

The type signature is unnecessary. Remove it or change it to

   `parallel_ :: Monad m => [m a] -> m ()`

for backward compatibility.

**Comment by odanoburu** [comment]
it [works](https://travis-ci.org/odanoburu/gf-rgl/builds/448808677)! thanks @Thomas-H

**Comment by Thomas-H** [comment]
> [it works](https://travis-ci.org/odanoburu/gf-rgl/jobs/448625886), thanks @Thomas-H !
> 
> what GHC versions is GF supposed to support? in MacOS I'm using 8.2, but in ubuntu trusty the version is 7.6.3 -- is this too old to be supported? 

In my tests GF still compiles with ghc-7.6.3. But Ubuntu 14.04 comes with Cabal-1.16 and `gf.cabal` nowadays requires Cabal>=1.22. (This was changed after the release of gf-3.9, which compiles out of the box on Ubuntu 14.04.)

I think the only reason for requiring Cabal>=1.20 is the use of `buildNumJobs` in `WebSetup.hs`. If you comment out that, you could still use an older version of Cabal...

**Comment by odanoburu** [comment]
> In my tests GF still compiles with ghc-7.6.3. But Ubuntu 14.04 comes with Cabal-1.16 and gf.cabal nowadays requires Cabal>=1.22. (This was changed after the release of gf-3.9, which compiles out of the box on Ubuntu 14.04.)

thanks for the info! this will be useful if we add a similar `.travis.yml` to `gf-core`.

@johnjcamilleri I've managed to build on windows using haskell and bash, but can't seem to build using the `.bat` script. I've [checked](https://travis-ci.org/odanoburu/gf-rgl/jobs/449045548) that I'm calling it correctly with a dummy script, so I guess there is some error, but the [error message](https://travis-ci.org/odanoburu/gf-rgl/jobs/449063103#L2916) is not very helpful.

**Comment by johnjcamilleri** [comment]
Well it doesn't surprise me that there's a bug, but yeah it's not obvious what's wrong. The first thing to try would be changing back the last copy command, essentially reversing 894c09d1b9c9fd8c51b116939425d3e24997c15e.
Other than that I'm not sure what else to try, and it will be pretty tedious to debug by having to use Travis each time, which is really why we need someone to test it locally.

Thanks for the great work though with setting up all this travis stuff!

**Comment by odanoburu** [comment]
@johnjcamilleri I've added a commit to #59 adding the windows build, which works for both haskell and bash scripts, while we wait for someone to test `Make.bat`. however, if someone on windows has git to clone this repo, I think she should also have bash (I think they are bundled together on windows), so this is not so terrible!

**Comment by johnjcamilleri** [comment]
> if someone on windows has git to clone this repo, I think she should also have bash (I think they are bundled together on windows), so this is not so terrible!

Yes that is true. The idea is that `Make.bat` would cater to those who don't have Haskell, git, or bash but still want to compile the RGL. Maybe those people don't exist.

Anyway I tried Krasimir's suggestion of using Wine but got very strange results. The majority of `Make.bat` was tested on a real Windows machine so I can't understand why it's giving errors about the most basic stuff like parsing flags and piping output ([see log here](https://github.com/GrammaticalFramework/gf-rgl/files/2540097/Make.bat.wine.log)). So I need some more bright ideas :/

**Comment by johnjcamilleri** [comment]
@odanoburu It seems the `xcopy` command introduced in 894c09d is definitely wrong. Can you reverse it and see if Travis succeeds?

**Comment by johnjcamilleri** [comment]
I'm managing to test the script now with Wine. 4b4a7ba9 already includes a bunch of improvements but I guess there are more to come. Either way it would be helpful to see the Travis output so far to see how it compares to the output I'm getting in Wine.

**Comment by odanoburu** [comment]
build is [failing](https://travis-ci.org/odanoburu/gf-rgl/jobs/449641653) now because of chocolatey, although their status page says everything is fine, the website is veeery slow here, and sometimes it timeouts, so I guess we'll have to wait.

**Comment by johnjcamilleri** [comment]
Typical! Well, as of a1705399 `Make.bat` might actually work. Wine has been helpful after all (maybe). So this is just a bump for you to merge in the latest from master.

**Comment by odanoburu** [comment]
same error, same [unhelpful log](https://travis-ci.org/odanoburu/gf-rgl/jobs/449840365) :/

**Comment by odanoburu** [comment]
this seems to be a pretty common error (see for example this [SO question](https://stackoverflow.com/questions/16821784/input-line-is-too-long-error-in-bat-file)), but I don't see how to fix it..

**Comment by johnjcamilleri** [comment]
If the length of the line is really a problem, one way to test is to just reduce the number of languages in the `lang` variable [here](https://github.com/GrammaticalFramework/gf-rgl/blob/916548a3618ce5e9c0bfefc386304503d188f170/Make.bat#L10). If it works for just a few languages then the solution is to process the languages in batches rather than all at once.

**Comment by odanoburu** [comment]
@johnjcamilleri I didn't think the number of languages would be a problem because the line length limit seemed to be big enough, but I got [somewhere](https://travis-ci.org/odanoburu/gf-rgl/jobs/450851928) by comment out half the languages. now I don't know if the problem is the command syntax or if the copy command is wrong in some way, but I suspect the later because I tried it in a windows 7 machine here and had the same error.

**Comment by johnjcamilleri** [comment]
This is definite progress!
So we'll need some changes to process the languages in batches to avoid the long line issue, and I'll see if I can figure out the problem with the copy command.

**Comment by odanoburu** [comment]
as per the SO thread, one of the solutions to the input line problem is to read the arguments from a file; if we could do this from `languages.csv` we'd be tackling to problems with one change!

**Comment by odanoburu** [comment]
seems to work now after 17bc505! https://travis-ci.org/odanoburu/gf-rgl/jobs/451007923

**Comment by johnjcamilleri** [comment]
Actually I don't think that would solve the problem.
The script essentially loops through a lot of modules and languages, building a big list of files to be compiled with GF. Whether this list is built from the CSV file or not, ultimately we'd still need to call GF with a long list of arguments and I assume this is the problem.

I've corrected the copy command but it turns out the code collecting the module names is still buggy. Nested loops seem to be especially problematic to get right...

**Comment by odanoburu** [comment]
yes, I thought so too, but misinterpreted this [piece of advice](http://support.microsoft.com/kb/830473):

> Modify programs that require long command lines so that they use a file that contains the parameter information, and then include the name of the file in the command line.

as in, you are supposed to hack your main program instead of the script (come on!?)

would it be acceptable to only make a `--langs=` argument mandatory and call it a day? (with a warning note in the docs about putting too many languages there, although I think it's probably very rare for anyone to need to compile more than 5 languages at once)

**Comment by johnjcamilleri** [comment]
Ok one more commit (ef2c348d), now I think we're ready.

- Actually what I said isn't completely true because GF is actually called individually for each module in this script. This is probably inefficient but has other advantages, such as getting around this long input line thing, but also if compilation of one module fails the whole thing doesn't fail.
- There was a devious bug where the control flow simply jumped out of a loop midway, meaning not actually all modules were being collected. This should hopefully be rectified now.
- A `--langs` argument should be easily doable (famous last words) to overwrite the hardcoded lang list, but I don't think this is needed as described above.
- Reading from `languages.csv` would be sweet... but honestly doing even the simplest things in a Windows batch file is so painful, I am quite sceptical that parsing CSV using only inbuilt commands is doable.

**Comment by johnjcamilleri** [comment]
> I am quite sceptical that parsing CSV using only inbuilt commands is doable.

Ok so a quick search reveals lots of results, maybe it won't be as bad as I thought. But I'm putting this under the heading "nice to have" and don't consider it necessary for this issue to be closed.

**Comment by odanoburu** [comment]
> Ok one more commit (ef2c348), now I think we're ready.

great, seems to work! (with all languages)
